apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-cm-yarmoshyk-com-key-pair
  namespace: course-management-dev
spec:
  secretName: prod-cm-yarmoshyk-com-key-pair
  issuerRef:
    name: letsencrypt-http01-prod
    kind: Issuer
  commonName: prod.cm-yarmoshyk.com
  dnsNames:
    - prod.cm-yarmoshyk.com
