apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-http01-prod
  namespace: course-management-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: yarmoshyk96@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-http01-key-pair
    solvers:
      - http01:
          ingress:
            class: nginx
