services:
  course-management:
    image: yaroslavyarmoshyk/course-management:dev
    build:
      context: .
    container_name: course-management-app
    ports:
      - 8080:8080
    depends_on:
      - course-management-db
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - DB_URL=jdbc:postgresql://course-management-db:5432/course-management
      - DB_USERNAME=cm-admin
      - DB_PASSWORD=alonso-321
      - SMTP_USERNAME=iryna19890909@gmail.com
      - SMTP_PASSWORD=eofhvaklswvejhto
      - ENCRYPTION_KEY=strong-$$key$$1991

  course-management-db:
    image: postgres:15.2-alpine
    container_name: course-management-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=cm-admin
      - POSTGRES_PASSWORD=alonso-321
      - POSTGRES_DB=course-management
