services:
  course-management:
    image: yaroslavyarmoshyk/course-management:dev
    build:
      context: .
    container_name: course-management-app
    depends_on:
      - course-management-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://course-management-db:5432/course-management
      - SPRING_DATASOURCE_USERNAME=cm-admin
      - SPRING_DATASOURCE_PASSWORD=alonso-321

  course-management-db:
    image: 'postgres:15.2-alpine'
    container_name: course-management-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=cm-admin
      - POSTGRES_PASSWORD=alonso-321
      - POSTGRES_DB=course-management
