apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
        - name: ${APP_NAME}
          image: ${IMAGE_REGISTRY}:${IMAGE_TAGS}
          ports:
            - containerPort: ${APP_PORT}
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
spec:
  ports:
    - port: ${APP_PORT}
      targetPort: ${APP_PORT}
  selector:
    app: ${APP_NAME}

parameters:
  - name: APP_NAME
    description: Application name to use for the buildconfig, deploymentconfig, and pods.
    required: true
  - name: APP_PORT
    description: Application running port
    required: true
  - name: IMAGE_REGISTRY
    description: Docker image registry
    required: true
  - name: IMAGE_TAGS
    description: Docker image tags
    required: true
