apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc-dev-db-claim
  namespace: course-management-dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-dev
  resources:
    requests:
      storage: 2Gi
