apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-dev-course-management
  namespace: course-management-dev
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: efs-dev
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-051a83001993fd582
