apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
  namespace: course-management-dev
spec:
  type: ClusterIP
  selector:
    component: postgres-dev
  ports:
    - port: 5432
      targetPort: 5432
