server:
  error:
    include-stacktrace: never

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: cm-admin
    password: alonso-321
    url: jdbc:postgresql://course-management-db:5432/course-management
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgres
      mode:
      continue-on-error: true
  flyway:
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true
    baseline-description: 'init'
    baseline-version: 0
  mail:
    host: smtp.gmail.com
    username: iryna19890909@gmail.com
    password: eofhvaklswvejhto
    port: 587
    protocol: smtp
    properties:
      "mail.transport.protocol": smtp
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true

course-management:
  url:
    base: http://localhost:8080

token:
  jwt:
    security-key: 77397A24432646294A404E635266556A586E327234753778214125442A472D4B6150645367566B59703373367638792F423F4528482B4D6251655468576D5A71
    expiration-time: 86_400_000 # 1 day
  confirmation:
    expiration-time:
      email: 2 # hours
      reset-password: 90 # minutes

encryption:
  key: strong-$key$1991
