spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://postgresql.yarmoshyk-redhat-dev.svc.cluster.local:5432/course-management
  mail:
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}

encryption:
  key: ${ENCRYPTION_KEY}
