apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-deployment
  namespace: course-management-${ENV}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: cm-backend
  template:
    metadata:
      labels:
        component: cm-backend
    spec:
      containers:
        - name: course-management
          image: yaroslavyarmoshyk/course-management:${COMMIT}
          imagePullPolicy: Always
          env:
            - name: ENCRYPTION_KEY
              value: ${ENCRYPTION_KEY}
            - name: SMTP_USERNAME
              value: ${SMTP_USERNAME}
            - name: SMTP_PASSWORD
              value: ${SMTP_PASSWORD}
            - name: DB_URL
              value: ${DB_URL}
            - name: DB_USERNAME
              value: ${DB_USERNAME}
            - name: DB_PASSWORD
              value: ${DB_PASSWORD}
            - name: SPRING_PROFILES_ACTIVE
              value: ${ENV}
          ports:
            - containerPort: 8080
