apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cm-ingress
spec:
  ingressClassName: external-nginx
  rules:
    - host: cm.yarmoshyk.io
      http:
        paths:
          - backend:
              service:
                name: cm-cluster-ip-service
                port:
                  number: 80
            pathType: Prefix
            path: /
