apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc-prod-db-claim
  namespace: course-management-prod
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-prod
  resources:
    requests:
      storage: 2Gi
