apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-prod-course-management
  namespace: course-management-prod
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: efs-prod
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0d176309e0702be40
