name: Deploy
on:
  workflow_call:
    inputs:
      env:
        description: The name of environment
        required: true
        type: string
jobs:
  job-information:
    uses: ./.github/workflows/job-information.yml
  test:
    needs: job-information
    uses: ./.github/workflows/testing.yml
    with:
      env: ${{ inputs.env }}
  push-to-docker-hub:
    needs: test
    secrets: inherit
    uses: ./.github/workflows/push-to-dockerhub.yml
    with:
      env: ${{ inputs.env }}
