name: Deploy to DEV
on:
  workflow_dispatch:
  push:
    branches: [develop, release]
env:
  REPOSITORY: ${{ github.repository }}
  TRIGGERING_ACTOR: ${{ github.triggering_actor }}
  SOURCE_BRANCH: ${{ github.ref_name }}
  COMMIT: ${{ github.workflow_sha }}
  EVENT: ${{ github.event_name}}
jobs:
  job-information:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was triggered by $TRIGGERING_ACTOR via $EVENT event to $SOURCE_BRANCH branch with commit $COMMIT"
  test:
    needs: job-information
    uses: ./.github/workflows/testing.yml
    with:
      env: dev
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build with Maven
        run: mvn package -DskipTests=true --file pom.xml -B

      - name: Check build result
        run: ls
  deploy:
    needs: build
    uses: ./.github/workflows/deploying.yml
