name: Deploy
on:
  workflow_call:
    inputs:
      env:
        description: The name of environment
        required: true
        type: string
env:
  ENV: ${{ inputs.env }}
jobs:
  job-information:
    uses: ./.github/workflows/job-information.yml
  test:
    needs: job-information
    uses: ./.github/workflows/testing.yml
    with:
      env: $ENV
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Build with Maven
        run: mvn package -DskipTests=true --file pom.xml -B
  deploy:
    needs: build
    uses: ./.github/workflows/deploying.yml
