name: Deploy artifact
on:
  workflow_call:
    inputs:
      env:
        description: The environment name
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - run: echo "The github environment is ${{ github.env }}"
      - name: Deploy
        run: echo "Deploying... "
