name: Generate allure report
on:
  workflow_call:
    inputs:
      allure-results-artifact-name:
        description: The name of folder which contains allure results
        required: true
        type: string
jobs:
  allure-report:
    runs-on: ubuntu-latest
    steps:
      - name: Download allure-results
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.allure-results-artifact-name }}
          path: allure-results
      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
      - name: Allure history information
        run: ls
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
