name: Job information
on:
  workflow_call:
env:
  REPOSITORY: ${{ github.repository }}
  TRIGGERING_ACTOR: ${{ github.triggering_actor }}
  SOURCE_BRANCH: ${{ github.ref_name }}
  COMMIT: ${{ github.workflow_sha }}
  EVENT: ${{ github.event_name}}
jobs:
  job-information:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was triggered by $TRIGGERING_ACTOR via $EVENT event to $SOURCE_BRANCH branch with commit $COMMIT"
